version: "2"
services:
  mariadb:
    image: "bitnami/mariadb:latest"
    volumes:
      - "mariadb_data:/bitnami"
    environment:
      - MARIADB_USER=blog_user
      - MARIADB_DATABASE=blog_waas
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: "bitnami/wordpress:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "wordpress_data:/bitnami"
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_BLOG_NAME=Blog WAAS
      - WORDPRESS_USERNAME=waas_user
      - WORDPRESS_PASSWORD=waas123
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
