version: "3.3"
services:
  wordpress:
    build: .
    restart: always
    ports:
      - 9080:80
    volumes:
      - ./wordpress_data/:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: waas_user
      WORDPRESS_DB_PASSWORD: waas123
      WORDPRESS_DB_NAME: blog_waas
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog_waas
      MYSQL_USER: waas_user
      MYSQL_PASSWORD: waas123
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports: 
      - 8888:8080
    
volumes:
  db_data: {}

